### ISSUE TITLE
Gradle wrapper missing in distribution

### ISSUE THREAD

**Issue by matshou** [yooksi/pz-zmod#14]
Distribution is generated without `gradle-wrapper.jar`.

**Comment by matshou** [comment]
@ChuckTheSheep I am unable to reproduce this issue, try running `assembleDist` again and see if the issue persists.

**Comment by Chuckleberry-Finn** [comment]
The issue still persists for me.

**Comment by matshou** [comment]
Did you try running `gradlew clean assembleDist` and verifying that there is no wrapper produced?

**Comment by Chuckleberry-Finn** [comment]
I only ran `gradlew assembleDist` this morning, but I just ran the mentioned command and this is the contents of gradle folder in  the build zip created.
![2021-02-20_23-30-07](https://user-images.githubusercontent.com/6071161/108615581-a0eb4900-73d3-11eb-878c-590a17cdc000.png)

**Comment by matshou** [comment]
I guess this doesn't matter that much since users are not suppose to be building their own distributions anyway, but I am still curious as to why this is happening. Can you confirm that you are checked out on `release/2.0` branch in the repository and that you are using the right directory? 

Also, we are using `assembleDist` shell script to create distributions (you can find it in run configurations) so you don't need to run `ls-git-ignore` and then `assembleDist` via Gradle. Thanks for helping to track this issue down.

**Comment by Chuckleberry-Finn** [comment]
I was actually on the previous version. The problem is fixed with `2.0`.

**Comment by matshou** [comment]
Resolved by 17def301730b03f0805906062631e607b20715ae
